#pragma once

#define SYS_EXIT      0
#define SYS_READ      1
#define SYS_WRITE     2
#define SYS_OPEN      3
#define SYS_CLOSE     4
#define SYS_PIPE      5
#define SYS_DUP       6
#define SYS_FCNTL     7
#define SYS_PREAD     8
#define SYS_PWRITE    9
#define SYS_SEEK      10
#define SYS_IOCTL     11
#define SYS_POLL      12
#define SYS_CHDIR     13
#define SYS_MKDIR     14
#define SYS_RMDIR     15
#define SYS_ACCESS    16
#define SYS_STAT      17
#define SYS_LSTAT     18
#define SYS_FSTAT     19
#define SYS_CHMOD     20
#define SYS_CHOWN     21
#define SYS_LINK      22
#define SYS_READLINK  23
#define SYS_UNLINK    24
#define SYS_RENAME    25
#define SYS_MOUNT     26
#define SYS_UMOUNT    27
#define SYS_MMAP      28
#define SYS_MUNMAP    29
#define SYS_FORK      30
#define SYS_EXECVE    31
#define SYS_WAIT      32
#define SYS_WAITPID   33
#define SYS_SLEEP     34
#define SYS_SIGNAL    35
#define SYS_SIGRETURN 36
#define SYS_KILL      37
#define SYS_TIME      38
