# This file contains options that get loaded and parsed by the bootloader
# They can be used to configure both the kernel and the bootloader

# Debug logging verbosity
debug=all # [all, minimal, none]

# Graphics options
video=graphics # [graphics, text, none]

# If we leave these undefined the bootloader will autodetect a resolution
# graphics.width = 1280
# graphics.height = 720
# graphics.bpp = 32 # bits per pixel

# font = /boot/font.psf

# The kernels console will print output to any number of devices
# List them out and separate by ','. The string can be at most 128 bytes long
console=/dev/ttyS0,/dev/tty0
