# This file contains options that get loaded and parsed by the bootloader
# They can be used to configure both the kernel and the bootloader

# Debug logging verbosity
debug=all # [all, minimal*, none]

# Graphics options
video=graphics # [graphics*, text, none]

# If we leave these undefined the bootloader will autodetect a resolution
# vesa.width = 1280
# vesa.height = 720
# vesa.bpp = 32 # bits per pixel

# text.font
