# Window manager config
background=/home/user/wall.qoi
cursors=/etc/cursors
font=/etc/ter-116n.psf

# Optional WM palette overrides (hex: #RRGGBB or 0xRRGGBB)
# color.background=#202020
# color.border=#737d7a
# color.title=#606b6b
# color.title_focus=#315f70
# color.client_bg=#000000
# color.title_text=#f2f1e8
# color.close_bg=#b7bbb6
# color.close_fg=#252a2a
